run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    enable:
      - shadow
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: ecommerce-backend

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - unused
    - gosec
    - bodyclose
    - nilerr

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
