// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "ecommerce-backend/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CartUseCase is an autogenerated mock type for the CartUseCase type
type CartUseCase struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, userID, req
func (_m *CartUseCase) AddItem(ctx context.Context, userID string, req *domain.CartItemRequest) (*domain.Cart, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 *domain.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.CartItemRequest) (*domain.Cart, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.CartItemRequest) *domain.Cart); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.CartItemRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *CartUseCase) ClearCart(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *CartUseCase) GetCart(ctx context.Context, userID string) (*domain.Cart, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *domain.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Cart, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Cart); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveItem provides a mock function with given fields: ctx, userID, productID
func (_m *CartUseCase) RemoveItem(ctx context.Context, userID string, productID string) (*domain.Cart, error) {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItem")
	}

	var r0 *domain.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Cart, error)); ok {
		return rf(ctx, userID, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Cart); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *CartUseCase) UpdateItem(ctx context.Context, userID string, productID string, quantity int) (*domain.Cart, error) {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *domain.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*domain.Cart, error)); ok {
		return rf(ctx, userID, productID, quantity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *domain.Cart); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, userID, productID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCartUseCase creates a new instance of CartUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartUseCase {
	mock := &CartUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
