// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "ecommerce-backend/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OrderUseCase is an autogenerated mock type for the OrderUseCase type
type OrderUseCase struct {
	mock.Mock
}

// Checkout provides a mock function with given fields: ctx, userID, req
func (_m *OrderUseCase) Checkout(ctx context.Context, userID string, req *domain.CreateOrderRequest) (*domain.OrderResponse, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 *domain.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.CreateOrderRequest) (*domain.OrderResponse, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.CreateOrderRequest) *domain.OrderResponse); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.CreateOrderRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMyOrders provides a mock function with given fields: ctx, userID, page, limit
func (_m *OrderUseCase) GetMyOrders(ctx context.Context, userID string, page int, limit int) (*domain.PaginatedOrderResponse, error) {
	ret := _m.Called(ctx, userID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetMyOrders")
	}

	var r0 *domain.PaginatedOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) (*domain.PaginatedOrderResponse, error)); ok {
		return rf(ctx, userID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) *domain.PaginatedOrderResponse); ok {
		r0 = rf(ctx, userID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaginatedOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, orderID, userID, isAdmin
func (_m *OrderUseCase) GetOrderByID(ctx context.Context, orderID string, userID string, isAdmin bool) (*domain.OrderResponse, error) {
	ret := _m.Called(ctx, orderID, userID, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *domain.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*domain.OrderResponse, error)); ok {
		return rf(ctx, orderID, userID, isAdmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *domain.OrderResponse); ok {
		r0 = rf(ctx, orderID, userID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, orderID, userID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelOrder provides a mock function with given fields: ctx, orderID, userID
func (_m *OrderUseCase) CancelOrder(ctx context.Context, orderID string, userID string) error {
	ret := _m.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateOrderStatus provides a mock function with given fields: ctx, orderID, req
func (_m *OrderUseCase) UpdateOrderStatus(ctx context.Context, orderID string, req *domain.UpdateOrderStatusRequest) error {
	ret := _m.Called(ctx, orderID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.UpdateOrderStatusRequest) error); ok {
		r0 = rf(ctx, orderID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderUseCase creates a new instance of OrderUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderUseCase {
	mock := &OrderUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
